table Returns
	lineageTag: d3006047-0277-4b6b-9d16-35e03b0ce287

	column Returned
		dataType: string
		lineageTag: c1a8cc10-d1c4-4238-a99c-ad0fe1e80e37
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 48db1450-2aae-4266-b52b-2e9af1521244
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 3fe0cdc6-336b-4a2f-bf46-b4712c29a4ad
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Returns = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Thinkpad\Downloads\archive\Global Superstore Data.xlsx"), null, true),
				    Returns_Sheet = Source{[Item="Returns",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Returns_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Returned", type text}, {"Order ID", type text}, {"Region", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

